#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2005-2006 Open Source Development Labs, Inc.
#               2005-2022 Mark Wong
#

usage()
{
    echo "Usage:"
    echo "  dbt7-pgsql-build-db [options]"
    echo "  dbt7-pgsql-build-db -h"
	echo ""
    echo "Options:"
    echo "  -p <postgresql parameters>    postgreSQL database parameters."
    echo "  -r                            drop existing database first thing"
    echo "  -s <scale>                    scale factor, default 1"
    echo "  -u                            run as an unprivileged PostgreSQL user"
}

PRIVILEGED=1
REBUILD_DB=0
SCALE=1

while getopts "hl:p:rs:tuw:f" OPT; do
	case $OPT in
	h)
		usage
		exit 0
		;;
	p)
		PARAMETERS=$OPTARG
		;;
	r)
		REBUILD_DB=1
		;;
	s)
		SCALE=$OPTARG
		;;
	u)
		PRIVILEGED=0
		;;
	esac
done

if [ -z $DBT7DBNAME ]; then
	echo "Error: DBT7DBNAME environment variable not defined"
	exit 1
fi

if [ $REBUILD_DB -eq 1 ] && [ -d $DBT7PGDATA ]; then
	if [ $PRIVILEGED -eq 1 ]; then
		echo "Restarting the database to reset database parameters..."
		dbt7-pgsql-stop-db
		dbt7-pgsql-start-db -p "$PARAMETERS" || exit 1
	fi
	dropdb $DBT7DBNAME
fi

dbt7-pgsql-load-data -s $SCALE
# Set the number of vacuumdb jobs to 1 (no parallelism) and let see
# if the system can support a greater value.
VACUUM_JOBS=1
# Based on server version, enable vaccumdb parallelism if that version
# is greater than or equal to 9.5.
PG_VERSION_NUM=$(psql -At -d $DBT7DBNAME -c "SHOW server_version_num")
PG_VERSION_NUM=$(( $PG_VERSION_NUM + 0 ))
if [ $PG_VERSION_NUM -ge 95000 ]; then
	# Set default vacuum jobs to 25 because this is the number of tables
	# present in the database. Setting the number of job to a value
	# greater than 25 won't bring any additional benefit.
	VACUUM_JOBS=25
	# If the number of CPUs is less than 25, then we set the vacuum job
	# number to that number of CPUs.
	if [ -f "/proc/stat" ]; then
		CPUS=$(grep cpu /proc/stat | wc -l)
		CPUS=$(( $CPUS - 1 ))
		if [ $CPUS -lt $VACUUM_JOBS ]; then
			VACUUM_JOBS=$CPUS
		fi
	fi
fi

VACUUM_OPTS="-z -F"

# Use vacuumdb's -j option only if VACUUM_JOBS is greater than 1.
if [ $VACUUM_JOBS -gt 1 ]; then
	VACUUM_OPTS+=" -j $VACUUM_JOBS"
fi

vacuumdb $VACUUM_OPTS -d $DBT7DBNAME || exit 1
