#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2015      2ndQuadrant, Ltd.
#               2002-2022 Mark Wong

create_table() {
	SQL=$1

	$PSQL << __EOF__
$SQL;
__EOF__
	return $?
}

if [ -z $DBT7DBNAME ]; then
	echo "Error: DBT7DBNAME environment variable not defined"
	exit 1
fi

PSQL="psql -v ON_ERROR_STOP=1 -X -A -t -d $DBT7DBNAME"

create_table "
CREATE TABLE store_sales (
    ss_sold_date_sk BIGINT,
    ss_sold_time_sk BIGINT,
    ss_item_sk BIGINT NOT NULL,
    ss_customer_sk BIGINT,
    ss_cdemo_sk BIGINT,
    ss_hdemo_sk BIGINT,
    ss_addr_sk BIGINT,
    ss_store_sk BIGINT,
    ss_promo_sk BIGINT,
    ss_ticket_number BIGINT NOT NULL,
    ss_quantity INTEGER,
    ss_wholesale_cost REAL,
    ss_list_price REAL,
	ss_sales_price NUMERIC(7, 2),
    ss_ext_discount_amt REAL,
	ss_ext_sales_price NUMERIC(7, 2),
    ss_ext_wholesale_cost REAL,
    ss_ext_list_price REAL,
    ss_ext_tax REAL,
    ss_coupon_amt REAL,
    ss_net_paid REAL,
    ss_net_paid_inc_tax REAL,
    ss_net_profit REAL
);" || exit 1

create_table "
CREATE TABLE store_returns (
    sr_returned_date_sk BIGINT,
    sr_return_time_sk BIGINT,
    sr_item_sk BIGINT NOT NULL,
    sr_customer_sk BIGINT,
    sr_cdemo_sk BIGINT,
    sr_hdemo_sk BIGINT,
    sr_addr_sk BIGINT,
    sr_store_sk BIGINT,
    sr_reason_sk BIGINT,
    sr_ticket_number BIGINT NOT NULL,
    sr_return_quantity INTEGER,
    sr_return_amt REAL,
    sr_return_tax REAL,
    sr_return_amt_inc_tax REAL,
    sr_fee REAL,
    sr_return_ship_cost REAL,
    sr_refunded_cash REAL,
    sr_reversed_charge REAL,
    sr_store_credit REAL,
    sr_net_loss REAL
);" || exit 1

create_table "
CREATE TABLE catalog_sales (
    cs_sold_date_sk BIGINT,
    cs_sold_time_sk BIGINT,
    cs_ship_date_sk BIGINT,
    cs_bill_customer_sk BIGINT,
    cs_bill_cdemo_sk BIGINT,
    cs_bill_hdemo_sk BIGINT,
    cs_bill_addr_sk BIGINT,
    cs_ship_customer_sk BIGINT,
    cs_ship_cdemo_sk BIGINT,
    cs_ship_hdemo_sk BIGINT,
    cs_ship_addr_sk BIGINT,
    cs_call_center_sk BIGINT,
    cs_catalog_page_sk BIGINT,
    cs_ship_mode_sk BIGINT,
    cs_warehouse_sk BIGINT,
    cs_item_sk BIGINT NOT NULL,
    cs_promo_sk BIGINT,
    cs_order_number BIGINT NOT NULL,
    cs_quantity INTEGER,
    cs_wholesale_cost REAL,
    cs_list_price REAL,
	cs_sales_price NUMERIC(7, 2),
    cs_ext_discount_amt REAL,
	cs_ext_sales_price NUMERIC(7, 2),
    cs_ext_wholesale_cost REAL,
    cs_ext_list_price REAL,
    cs_ext_tax REAL,
    cs_coupon_amt REAL,
    cs_ext_ship_cost REAL,
    cs_net_paid REAL,
    cs_net_paid_inc_tax REAL,
    cs_net_paid_inc_ship REAL,
    cs_net_paid_inc_ship_tax REAL,
    cs_net_profit REAL
);" || exit 1

create_table "
CREATE TABLE catalog_returns (
    cr_returned_date_sk BIGINT,
    cr_returned_time_sk BIGINT,
    cr_item_sk BIGINT NOT NULL,
    cr_refunded_customer_sk BIGINT,
    cr_refunded_cdemo_sk BIGINT,
    cr_refunded_hdemo_sk BIGINT,
    cr_refunded_addr_sk BIGINT,
    cr_returning_customer_sk BIGINT,
    cr_returning_cdemo_sk BIGINT,
    cr_returning_hdemo_sk BIGINT,
    cr_returning_addr_sk BIGINT,
    cr_call_center_sk BIGINT,
    cr_catalog_page_sk BIGINT,
    cr_ship_mode_sk BIGINT,
    cr_warehouse_sk BIGINT,
    cr_reason_sk BIGINT,
    cr_order_number BIGINT NOT NULL,
    cr_return_quantity INTEGER,
    cr_return_amount REAL,
    cr_return_tax REAL,
    cr_return_amt_inc_tax REAL,
    cr_fee REAL,
    cr_return_ship_cost REAL,
    cr_refunded_cash REAL,
    cr_reversed_charge REAL,
    cr_store_credit REAL,
    cr_net_loss REAL
);" || exit 1

create_table "
CREATE TABLE web_sales (
    ws_sold_date_sk BIGINT,
    ws_sold_time_sk BIGINT,
    ws_ship_date_sk BIGINT,
    ws_item_sk BIGINT NOT NULL,
    ws_bill_customer_sk BIGINT,
    ws_bill_cdemo_sk BIGINT,
    ws_bill_hdemo_sk BIGINT,
    ws_bill_addr_sk BIGINT,
    ws_ship_customer_sk BIGINT,
    ws_ship_cdemo_sk BIGINT,
    ws_ship_hdemo_sk BIGINT,
    ws_ship_addr_sk BIGINT,
    ws_web_page_sk BIGINT,
    ws_web_site_sk BIGINT,
    ws_ship_mode_sk BIGINT,
    ws_warehouse_sk BIGINT,
    ws_promo_sk BIGINT,
    ws_order_number BIGINT NOT NULL,
    ws_quantity INTEGER,
    ws_wholesale_cost REAL,
    ws_list_price REAL,
	ws_sales_price NUMERIC(7, 2),
    ws_ext_discount_amt REAL,
	ws_ext_sales_price NUMERIC(7, 2),
    ws_ext_wholesale_cost REAL,
    ws_ext_list_price REAL,
    ws_ext_tax REAL,
    ws_coupon_amt REAL,
    ws_ext_ship_cost REAL,
    ws_net_paid REAL,
    ws_net_paid_inc_tax REAL,
    ws_net_paid_inc_ship REAL,
    ws_net_paid_inc_ship_tax REAL,
    ws_net_profit REAL
);" || exit 1

create_table "
CREATE TABLE web_returns (
    wr_returned_date_sk BIGINT,
    wr_returned_time_sk BIGINT,
    wr_item_sk BIGINT NOT NULL,
    wr_refunded_customer_sk BIGINT,
    wr_refunded_cdemo_sk BIGINT,
    wr_refunded_hdemo_sk BIGINT,
    wr_refunded_addr_sk BIGINT,
    wr_returning_customer_sk BIGINT,
    wr_returning_cdemo_sk BIGINT,
    wr_returning_hdemo_sk BIGINT,
    wr_returning_addr_sk BIGINT,
    wr_web_page_sk BIGINT,
    wr_reason_sk BIGINT,
    wr_order_number BIGINT NOT NULL,
    wr_return_quantity INTEGER,
    wr_return_amt REAL,
    wr_return_tax REAL,
    wr_return_amt_inc_tax REAL,
    wr_fee REAL,
    wr_return_ship_cost REAL,
    wr_refunded_cash REAL,
    wr_reversed_charge REAL,
    wr_account_credit REAL,
    wr_net_loss REAL
);" || exit 1

create_table "
CREATE TABLE inventory (
    inv_date_sk BIGINT NOT NULL,
    inv_item_sk BIGINT NOT NULL,
    inv_warehouse_sk BIGINT NOT NULL,
    inv_quantity_on_hand INTEGER
);" || exit 1

create_table "
CREATE TABLE store (
    s_store_sk BIGINT NOT NULL,
    s_store_id CHAR(16) NOT NULL,
    s_rec_start_date DATE,
    s_rec_end_date DATE,
    s_closed_date_sk BIGINT,
    s_store_name VARCHAR(50),
    s_number_employees INTEGER,
    s_floor_space INTEGER,
    s_hours CHAR(20),
    s_manager VARCHAR(40),
    s_market_id INTEGER,
    s_geography_class VARCHAR(100),
    s_market_desc VARCHAR(100),
    s_market_manager VARCHAR(40),
    s_division_id INTEGER,
    s_division_name VARCHAR(50),
    s_company_id INTEGER,
    s_company_name VARCHAR(50),
    s_street_number VARCHAR(10),
    s_street_name VARCHAR(60),
    s_street_type CHAR(15),
    s_suite_number CHAR(10),
    s_city VARCHAR(60),
    s_county VARCHAR(30),
    s_state CHAR(2),
    s_zip CHAR(10),
    s_country VARCHAR(20),
    s_gmt_offset REAL,
    s_tax_percentage REAL
);" || exit 1

create_table "
CREATE TABLE call_center (
    cc_call_center_sk BIGINT NOT NULL,
    cc_call_center_id CHAR(16) NOT NULL,
    cc_rec_start_date DATE,
    cc_rec_end_date DATE,
    cc_closed_date_sk INTEGER,
    cc_open_date_sk INTEGER,
    cc_name VARCHAR(50),
    cc_class VARCHAR(50),
    cc_employees INTEGER,
    cc_sq_ft INTEGER,
    cc_hours CHAR(20),
    cc_manager VARCHAR(40),
    cc_mkt_id INTEGER,
    cc_mkt_class CHAR(50),
    cc_mkt_desc VARCHAR(100),
    cc_market_manager VARCHAR(40),
    cc_division INTEGER,
    cc_division_name VARCHAR(50),
    cc_company INTEGER,
    cc_company_name CHAR(50),
    cc_street_number CHAR(10),
    cc_street_name VARCHAR(60),
    cc_street_type CHAR(15),
    cc_suite_number CHAR(10),
    cc_city VARCHAR(60),
    cc_county VARCHAR(30),
    cc_state CHAR(2),
    cc_zip CHAR(10),
    cc_country VARCHAR(20),
    cc_gmt_offset REAL,
    cc_tax_percentage REAL
);" || exit 1

create_table "
CREATE TABLE catalog_page (
    cp_catalog_page_sk BIGINT NOT NULL,
    cp_catalog_page_id CHAR(16) NOT NULL,
    cp_start_date_sk INTEGER,
    cp_end_date_sk INTEGER,
    cp_department VARCHAR(50),
    cp_catalog_number INTEGER,
    cp_catalog_page_number INTEGER,
    cp_description VARCHAR(100),
    cp_type VARCHAR(100)
);" || exit 1

create_table "
CREATE TABLE web_site (
    web_site_sk BIGINT NOT NULL,
    web_site_id CHAR(16) NOT NULL,
    web_rec_start_date DATE,
    web_rec_end_date DATE,
    web_name VARCHAR(50),
    web_open_date_sk BIGINT,
    web_close_date_sk BIGINT,
    web_class VARCHAR(50),
    web_manager VARCHAR(40),
    web_mkt_id INTEGER,
    web_mkt_class VARCHAR(50),
    web_mkt_desc VARCHAR(100),
    web_market_manager VARCHAR(40),
    web_company_id INTEGER,
    web_company_name CHAR(50),
    web_street_number CHAR(10),
    web_street_name VARCHAR(60),
    web_street_type CHAR(15),
    web_suite_number CHAR(10),
    web_city VARCHAR(60),
    web_county VARCHAR(30),
    web_state CHAR(2),
    web_zip CHAR(10),
    web_country VARCHAR(20),
    web_gmt_offset REAL,
    web_tax_percentage REAL
);" || exit 1

create_table "
CREATE TABLE web_page (
    wp_web_page_sk BIGINT NOT NULL,
    wp_web_page_id CHAR(16) NOT NULL,
    wp_rec_start_date DATE,
    wp_rec_end_date DATE,
    wp_creation_date_sk BIGINT,
    wp_access_date_sk BIGINT,
    wp_autogen_flag CHAR(1),
    wp_customer_sk BIGINT,
    wp_url VARCHAR(100),
    wp_type CHAR(50),
    wp_char_count INTEGER,
    wp_link_count INTEGER,
    wp_image_count INTEGER,
    wp_max_ad_count INTEGER
);" || exit 1

create_table "
CREATE TABLE warehouse (
    w_warehouse_sk BIGINT NOT NULL,
    w_warehouse_id CHAR(16) NOT NULL,
    w_warehouse_name VARCHAR(20),
    w_warehouse_sq_ft INTEGER,
    w_street_number CHAR(10),
    w_street_name VARCHAR(60),
    w_street_type CHAR(15),
    w_suite_number CHAR(10),
    w_city VARCHAR(60),
    w_county VARCHAR(30),
    w_state CHAR(2),
    w_zip CHAR(10),
    w_country VARCHAR(20),
    w_gmt_offset REAL
);" || exit 1

create_table "
CREATE TABLE customer (
    c_customer_sk BIGINT NOT NULL,
    c_customer_id CHAR(16) NOT NULL,
    c_current_cdemo_sk BIGINT,
    c_current_hdemo_sk BIGINT,
    c_current_addr_sk BIGINT,
    c_first_shipto_date_sk BIGINT,
    c_first_sales_date_sk BIGINT,
    c_salutation CHAR(10),
    c_first_name CHAR(20),
    c_last_name CHAR(30),
    c_preferred_cust_flag CHAR(1),
    c_birth_day INTEGER,
    c_birth_month INTEGER,
    c_birth_year INTEGER,
    c_birth_country VARCHAR(20),
    c_login CHAR(13),
    c_email_address CHAR(50),
    c_last_review_date_sk BIGINT
);" || exit 1

create_table "
CREATE TABLE customer_address (
    ca_address_sk BIGINT NOT NULL,
    ca_address_id CHAR(16) NOT NULL,
    ca_street_number CHAR(10),
    ca_street_name VARCHAR(60),
    ca_street_type CHAR(15),
    ca_suite_number CHAR(10),
    ca_city VARCHAR(60),
    ca_county VARCHAR(30),
    ca_state CHAR(2),
    ca_zip CHAR(10),
    ca_country VARCHAR(20),
    ca_gmt_offset REAL,
    ca_location_type CHAR(20)
);" || exit 1

create_table "
CREATE TABLE customer_demographics (
    cd_demo_sk BIGINT NOT NULL,
    cd_gender CHAR(1),
    cd_marital_status CHAR(1),
    cd_education_status CHAR(20),
    cd_purchase_estimate INTEGER,
    cd_credit_rating CHAR(10),
    cd_dep_count INTEGER,
    cd_dep_employed_count INTEGER,
    cd_dep_college_count INTEGER
);" || exit 1

create_table "
CREATE TABLE date_dim (
    d_date_sk BIGINT NOT NULL,
    d_date_id CHAR(16) NOT NULL,
    d_date DATE,
    d_month_seq INTEGER,
    d_week_seq INTEGER,
    d_quarter_seq INTEGER,
    d_year INTEGER,
    d_dow INTEGER,
    d_moy INTEGER,
    d_dom INTEGER,
    d_qoy INTEGER,
    d_fy_year INTEGER,
    d_fy_quarter_seq INTEGER,
    d_fy_week_seq INTEGER,
    d_day_name CHAR(9),
    d_quarter_name CHAR(6),
    d_holiday CHAR(1),
    d_weekend CHAR(1),
    d_following_holiday CHAR(1),
    d_first_dom INTEGER,
    d_last_dom INTEGER,
    d_same_day_ly INTEGER,
    d_same_day_lq INTEGER,
    d_current_day CHAR(1),
    d_current_week CHAR(1),
    d_current_month CHAR(1),
    d_current_quarter CHAR(1),
    d_current_year CHAR(1)
);" || exit 1

create_table "
CREATE TABLE household_demographics (
    hd_demo_sk BIGINT NOT NULL,
    hd_income_band_sk BIGINT,
    hd_buy_potential CHAR(15),
    hd_dep_count INTEGER,
    hd_vehicle_count INTEGER
);" || exit 1

create_table "
CREATE TABLE item (
    i_item_sk BIGINT NOT NULL,
    i_item_id CHAR(16) NOT NULL,
    i_rec_start_date DATE,
    i_rec_end_date DATE,
    i_item_desc VARCHAR(200),
    i_current_price REAL,
    i_wholesale_cost REAL,
    i_brand_id INTEGER,
    i_brand CHAR(50),
    i_class_id INTEGER,
    i_class CHAR(50),
    i_category_id INTEGER,
    i_category CHAR(50),
    i_manufact_id INTEGER,
    i_manufact CHAR(50),
    i_size CHAR(20),
    i_formulation CHAR(20),
    i_color CHAR(20),
    i_units CHAR(10),
    i_container CHAR(10),
    i_manager_id INTEGER,
    i_product_name CHAR(50)
);" || exit 1

create_table "
CREATE TABLE income_band (
    ib_income_band_sk BIGINT NOT NULL,
    ib_lower_bound INTEGER,
    ib_upper_bound INTEGER
);" || exit 1

create_table "
CREATE TABLE promotion (
    p_promo_sk BIGINT NOT NULL,
    p_promo_id CHAR(16) NOT NULL,
    p_start_date_sk INTEGER,
    p_end_date_sk INTEGER,
    p_item_sk INTEGER,
    p_cost REAL,
    p_response_target INTEGER,
    p_promo_name CHAR(50),
    p_channel_dmail CHAR(1),
    p_channel_email CHAR(1),
    p_channel_catalog CHAR(1),
    p_channel_tv CHAR(1),
    p_channel_radio CHAR(1),
    p_channel_press CHAR(1),
    p_channel_event CHAR(1),
    p_channel_demo CHAR(1),
    p_channel_details VARCHAR(100),
    p_purpose CHAR(15),
    p_discount_active CHAR(1)
);" || exit 1

create_table "
CREATE TABLE reason (
    r_reason_sk BIGINT NOT NULL,
    r_reason_id CHAR(16) NOT NULL,
    r_reason_desc CHAR(100)
);" || exit 1

create_table "
CREATE TABLE ship_mode (
    sm_ship_mode_sk BIGINT NOT NULL,
    sm_ship_mode_id CHAR(16) NOT NULL,
    sm_type CHAR(30),
    sm_code CHAR(10),
    sm_carrier CHAR(20),
    sm_contract CHAR(20)
);" || exit 1

create_table "
CREATE TABLE time_dim (
    t_time_sk BIGINT NOT NULL,
    t_time_id CHAR(16) NOT NULL,
    t_time INTEGER,
    t_hour INTEGER,
    t_minute INTEGER,
    t_second INTEGER,
    t_am_pm CHAR(2),
    t_shift CHAR(20),
    t_sub_shift CHAR(20),
    t_meal_time CHAR(20)
);" || exit 1

create_table "
CREATE TABLE time_statistics (
    stream INTEGER NOT NULL,
    query INTEGER NOT NULL,
    template VARCHAR(22) NOT NULL,
    seed BIGINT NOT NULL,
    s_time TIMESTAMP,
    e_time TIMESTAMP
);" || exit 1

$PSQL << __EOF__
CREATE SEQUENCE dataset
MINVALUE 1
START WITH 1;
SELECT nextval('dataset');
__EOF__
