#!/bin/sh

# Start a DBT-7 test.

usage()
{
	echo "usage: $0 [DBMS [SCALE]]"
}

which docker > /dev/null 2>&1
if [ $? -ne 0 ]; then
	echo "docker not in path"
	exit 1
fi

if [ $# -lt 1 ]; then
	usage
	exit 1
fi

DBMS=$1

SCALE=1
if [ $# -gt 1 ]; then
	SCALE=$2
fi

DOCKER_NAME="dbt7-${DBMS}-0"
DOCKER_TAG="dbt7-${DBMS}"
DOCKERDIR=`dirname $0`

# Use the return code from `docker inspect` to determine if the docker image
# needs to be created.
docker inspect $DOCKER_TAG > /dev/null
if [ $? -ne 0 ]; then
	${DOCKERDIR}/build-${DBMS} || exit 1
fi

docker run --rm --name $DOCKER_NAME --shm-size=128m $DOCKER_TAG \
		dbt7-run-workload -g -a pgsql -s 1 -d postgresql \
					-i templates-postgresql.lst -n 3 -o /tmp/results
if [ $? -ne 0 ]; then
	usage
	exit 1
fi
