#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright The DBT-7 Authors
#

usage()
{
	echo "`basename $0` is the DBT-7 report generator"
	echo ""
	echo "Usage:"
	echo "  `basename $0` [OPTIONS]"
	echo ""
	echo "General options:"
	echo "  -i PATH     results directory"
}

create_sar_page()
{
	local TITLE=$1
	local TAG=$2
	local DIR=$3
	local ODIR=$4

	mkdir -p $ODIR

	cat > ${ODIR}/index.rst << __EOF__
================================================================================
Database Test 7 $TITLE $TAG Charts
================================================================================

$(show_images $DIR $TAG)
__EOF__
}

sar_links() {
	TESTDIR=$1

	THISDIR="${INDIR}/${TESTDIR}"
	if [ ! -f "${THISDIR}/sar_raw.out" ]; then
		return
	fi

	cat << __EOF__
\`CPU <${TESTDIR}/cpu/>\`__ \`Memory <${TESTDIR}/mem/>\`__ \`Blockdev <${TESTDIR}/blockdev/>\`__ \`Network <${TESTDIR}/net/>\`__ \`Swap <${TESTDIR}/swap/>\`__
__EOF__

	create_sar_page $TESTDIR cpu $THISDIR ${THISDIR}/cpu
	create_sar_page $TESTDIR mem $THISDIR ${THISDIR}/mem
	create_sar_page $TESTDIR blockdev $THISDIR ${THISDIR}/blockdev
	create_sar_page $TESTDIR net $THISDIR ${THISDIR}/net
	create_sar_page $TESTDIR swap $THISDIR ${THISDIR}/swap
}

show_images()
{
	DIR=$1
	TAG=$2

	CHARTS=$(cd $DIR && find */ -name "sar-${TAG}*.png")
	for CHART in $CHARTS; do
		echo ".. image:: ../${CHART}"
		echo "   :target: ../${CHART}"
		echo "   :width: 100%"
		echo ""
	done
}

write_system_stats()
{
	TEST=$1

	cat << __EOF__

System Statistics
=================

Processor Statistics
--------------------

__EOF__

	for PNGFILE in ${OUTDIR}/${TEST}/sar/sar-cpu?*.png; do
		cat << __EOF__
.. image:: ${TEST}/sar/`basename $PNGFILE`
   :width: 100%

__EOF__
	done

	cat << __EOF__

Block Device Statistics
-----------------------

__EOF__

	for PNGFILE in ${OUTDIR}/${TEST}/sar/sar-blockdev-*-*.png; do
		cat << __EOF__
.. image:: ${TEST}/sar/`basename $PNGFILE`
   :width: 100%

__EOF__
	done
}

while getopts hi: OPT; do
	case $OPT in
		h)
			usage
			exit 0
			;;
		i)
			INDIR=$OPTARG
			OUTDIR=$INDIR
			;;
		\?)
			usage
			exit 1
			;;
	esac
done

if [ "x$INDIR" = "x" ]; then
	echo "Error: Specify dbt7 results directory with -i"
	exit 1
fi

if [ "x$OUTDIR" = "x" ]; then
	OUTDIR=$INDIR
fi

REPORT="${OUTDIR}/report.rst"
REPORTLOAD="${OUTDIR}/report-load.rst"
REPORTPOWER="${OUTDIR}/report-power.rst"
REPORTTHROUGHPUT="${OUTDIR}/report-throughput.rst"
ERRLOG="${OUTDIR}/error.txt"

DIRLOAD="${INDIR}/load"
DIRPOWER="${INDIR}/power"
DIRTHROUGHPUT="${INDIR}/throughput"

CONFIGFILE="${INDIR}/config.txt"
CPU_MODEL=`grep "^model" $CONFIGFILE | cut -d ":" -f2-`
CPUS=`grep ^cpus $CONFIGFILE | cut -d ":" -f2-`
DBMS=$(grep "^dbms" $CONFIGFILE | awk '{print $2}')
KERNEL=`grep ^kernel $CONFIGFILE | cut -d ":" -f2-`
OS=`grep ^distribution $CONFIGFILE | cut -d ":" -f2-`
RAM=`grep ^memory $CONFIGFILE | cut -d ":" -f2-`
SCALE=`grep ^scale $CONFIGFILE | cut -d ":" -f2-`

dbt7-plot-results -i ${INDIR}/power/time_statistics.csv -o ${OUTDIR} \
		2> /dev/null &
for DIR in load power throughput; do
	if [ ! -d "${INDIR}/${DIR}" ]; then
		continue
	fi
	SARDIR="${OUTDIR}/${DIR}/sar"
	mkdir -p $SARDIR
	dbt-plot-sar-cpu ${INDIR}/${DIR}/sar-cpu.csv $SARDIR 2> /dev/null &
	dbt-plot-sar-blockdev ${INDIR}/${DIR}/sar-blockdev.csv $SARDIR 2> /dev/null &
	dbt-plot-sar-mem -i ${INDIR}/${DIR}/sar-mem.csv -o $SARDIR 2> /dev/null &
	dbt-plot-sar-swap ${INDIR}/${DIR}/sar-swap.csv $SARDIR 2> /dev/null &
done
for PIDSTATFILE in $(find $INDIR -name pidstat.txt); do
	DIRNAME="$(dirname $PIDSTATFILE)"
	(cd $DIRNAME && dbt-process-pidstat $PIDSTATFILE 2> /dev/null) &
done

wait

SUMMARY="${INDIR}/summary.rst"
if [ ! -f "$SUMMARY" ]; then
	if [ -d "$DIRLOAD" ]; then
		FLAGS="-1 $DIRLOAD"
	fi
	if [ -d "$DIRPOWER" ]; then
		FLAGS="$FLAGS -2 $DIRPOWER"
	fi
	if [ -d "$DIRTHROUGHPUT" ]; then
		FLAGS="$FLAGS -3 $DIRTHROUGHPUT"
	fi
	dbt7-post-process -s $SCALE $FLAGS -o $INDIR
fi

README="${DIRPOWER}/readme.txt"
if [ -f "$README" ]; then
	DBVER=`head -n 1 $README`
fi
if [ "x$DBVER" = "x" ]; then
	README="${DIRTHROUGHPUT}/readme.txt"
	DBVER=`head -n 1 $README`
fi

cat << __EOF__ > $REPORT
$(cat $SUMMARY)

Power Test
==========

.. image:: power.png
   :alt: Missing Power Test Query Times
   :width: 100%

System Configuration
====================

Hardware Information
--------------------

* CPU Type: $CPU_MODEL
* Total Processors: $CPUS
* Memory: $RAM KB RAM

Software Information
--------------------

* Operating System: $OS $KERNEL
* Database Server: $DBVER

System Statistics
=================

Load Test
---------

* Charts: $(sar_links load)

Power Test
----------

* Charts: $(sar_links power)

Throughput Test
---------------

* Charts: $(sar_links throughput)

$(dbt7-${DBMS}-report -i $INDIR 2> /dev/null)
__EOF__

#
# Generate Load Test Report
#

cat << __EOF__ > $REPORTLOAD
=========================
Database Test 7 Load Test
=========================

__EOF__

R --slave --no-save << __EOF__ >> $REPORTLOAD
df <- read.csv("${DIRLOAD}/time_statistics.csv", header=TRUE)
df <- df[order(df\$e_time),]
cat("================  ===================  ===================  ===============\n")
cat("Phase             Start Timestamp      End Timestamp        Elapsed Time\n")
cat("================  ===================  ===================  ===============\n")
for (i in 1:nrow(df)) {
  cat(sprintf("%16s  %s  %s  %s\n",
      df[i,]\$template, df[i,]\$s_time, df[i,]\$e_time, df[i,]\$elapsed_time))
}
cat("================  ===================  ===================  ===============\n")

$(write_system_stats load)
__EOF__

#
# Generate Power Test Report
#

R --slave --no-save << __EOF__ >> $REPORTPOWER
==========================
Database Test 7 Power Test
==========================

$(write_system_stats power)
__EOF__

#
# Generate Throghput Test Report
#

R --slave --no-save << __EOF__ >> $REPORTTHROUGHPUT
===============================
Database Test 7 Throughput Test
===============================

$(write_system_stats throughput)
__EOF__

echo "Generated text file reports:"
ls -1v ${OUTDIR}/*.rst
echo ""

#
# Convert reStructuredText files to HTML and PDF.
#

RST2HTML5=""
for POSSIBILITY in rst2html5.py rst2html5; do
	which $POSSIBILITY > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		RST2HTML5="$POSSIBILITY"
		break
	fi
done

if [ ! "x${RST2HTML5}" = "x" ]; then
	# pandoc can't properly convert multi-cell table headings from rst but
	# Sphinx's rst2html can. Then pandoc can convert multi-cell table headings
	# from html to pdf.
	$RST2HTML5 ${OUTDIR}/report.rst ${OUTDIR}/report.html 2> /dev/null &
	for RST in $(find $INDIR -name "*.rst"); do
		NAME="${RST%.*}"
		(cd $(dirname $RST) && \
				$RST2HTML5 $(basename $RST) ${NAME}.html 2> /dev/null) &
	done
	wait

	echo "Generated HTML reports:"
	ls -1v ${OUTDIR}/*.html
	echo ""

	# A pdf could be produced other ways, but I believe pandoc produces the most
	# minimally styled LaTeX looking document, as opposed to using rst2latex,
	# with default settings.
	which pandoc > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		(cd $OUTDIR && \
				pandoc -s report.html -f html -t pdf \
						-o report.pdf 2> /dev/null) &
		for HTML in $(find $INDIR -name "*.html"); do
			NAME="${HTML%.*}"
			(cd $(dirname $HTML) && \
					pandoc -s $(basename $HTML) -f html -t pdf -o ${NAME}.pdf \
							2> /dev/null) &
		done
		wait

		echo "Generated PDF reports:"
		ls -1v ${OUTDIR}/*.pdf
		echo ""
	else
		echo "pandoc required to generate pdf report"
		exit 1
	fi
else
	echo "rst2html5 required to generate html report"
	exit 1
fi
